name: test
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.6

      - name: Set up go
        uses: actions/setup-go@v5.0.1
        with:
          go-version: 1.23.0

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test ./...
